[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flowertune-llm"
version = "1.0.0"
description = "FlowerTune LLM: Federated LLM Fine-tuning with Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]==1.12.0",
    "flwr-datasets>=0.3.0",
    "trl==0.8.1",
    "bitsandbytes==0.43.0",
    "scipy==1.13.0",
    "peft==0.6.2",
    "fschat[model_worker,webui]==0.2.35",
    "transformers==4.41.1",
    "sentencepiece==0.2.0",
    "omegaconf==2.3.0",
    "hf_transfer==0.1.8",
]


[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "fedllm.server_app:app"
clientapp = "fedllm.client_app:app"

[tool.flwr.app.config]
num-server-rounds = 1
num-supernodes = 10

# Define dataset
dataset.name = "vicgalle/alpaca-gpt4"

# Define model settings
model.name = "Qwen/Qwen2.5-1.5B-Instruct" 
model.quantization = 4
model.gradient-checkpointing = true
model.flash_attention = true

# Define LoRA settings
model.lora.lora-r = 8 
model.lora.lora-alpha = 16
model.lora.lora-dropout = 0.05
model.lora.lora-target-modules = "q_proj, k_proj, v_proj, o_proj, gate_proj, up_proj, down_proj"

# Define training settings
train.save-every-round = 5 
train.learning-rate-max = 5e-5
train.learning-rate-min = 1e-6
train.seq-length = 256
train.prompt_template_name = "alpaca"
train.train_on_inputs = true
train.verbose = false

# Define training agruments for HF Trainer
train.training-arguments.output-dir = "" 
train.training-arguments.learning-rate = 3e-4
train.training-arguments.per-device-train-batch-size = 4
train.training-arguments.gradient-accumulation-steps = 1
train.training-arguments.per-device-eval-batch-size = 2
train.training-arguments.eval-accumulation-steps = 1
train.training-arguments.logging-steps = 10
train.training-arguments.num-train-epochs = 1
train.training-arguments.max-steps = 10
train.training-arguments.save-steps = 1000
train.training-arguments.save-total-limit = 10
train.training-arguments.gradient-checkpointing = true
train.training-arguments.lr-scheduler-type = "cosine"
train.training-arguments.warmup-steps = 0
train.training-arguments.do-train = true
train.training-arguments.do-eval = true
train.training-arguments.dataloader-drop-last = false
train.training-arguments.eval-strategy = "epoch"
train.training-arguments.save-strategy = "no"
train.training-arguments.ddp-find-unused-parameters = false
train.training-arguments.group-by-length = true
train.training-arguments.report-to = "wandb"

# Define local training settings 
train.strategy.fraction-fit = 0.1 
train.strategy.fraction-evaluate = 0.1

[tool.flwr.federations]
default = "local-simulation"

[tool.flwr.federations.local-simulation]
options.num-supernodes = 10
options.backend.client-resources.num-cpus = 8
options.backend.client-resources.num-gpus = 1.0